spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_database
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    function:
      scan:
        enabled: false
    stream:
      function:
        definition: paymentProcessor;inventoryEventConsumer
      bindings:
        paymentProcessor-in-0:
          destination: order-event
        paymentProcessor-out-0:
          destination: payment-event
        inventoryEventConsumer-in-0:
          destination: inventory-event
server:
  port: 8083
