spring:
  datasource:
    url: jdbc:postgresql://10.10.10.12:5444/hpuat?currentSchema=dwh
    driver-class-name: org.postgresql.Driver
    username: dwh
    password: dwh
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081

logging:
  file:
    name: logs/hp-rc-service.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd_HH-mm}.gz
      max-history: 30
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    root: INFO
    com.cdac.hp.rc: DEBUG
