server:
  port: 8082

spring:
  application:
    name: user-service


logging:
  level:
    org.springframework.boot.env: DEBUG    # Shows config loading
    org.springframework.core.env: DEBUG    # Shows property resolution
    com.hipradeep: TRACE                   # Your package for custom logging

resilience4j:
  circuitbreaker:
    instances:
      orderService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      orderService:
        maxAttempts: 3
        waitDuration: 1s
      orderServiceJitter:
        maxAttempts: 3
        waitDuration: 1s
        enableRandomizedWait: true
        randomizedWaitFactor: 0.5
  ratelimiter:
    instances:
      orderService:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 0s