server:
  port: 8083

spring:
  application:
    name: order-service


logging:
  level:
    org.springframework.boot.env: DEBUG    # Shows config loading
    org.springframework.core.env: DEBUG    # Shows property resolution
    com.hipradeep: TRACE                   # Your package for custom logging

resilience4j:
  ratelimiter:
    instances:
      backendA:
        limitForPeriod: 5
        limitRefreshPeriod: 60s
        timeoutDuration: 0