server:
  port: 8083

spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888/


logging:
  level:
    org.springframework.boot.env: DEBUG    # Shows config loading
    org.springframework.core.env: DEBUG    # Shows property resolution
    com.hipradeep: TRACE                   # Your package for custom logging