spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order_database
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    function:
      scan:
        enabled: false
    stream:
      function:
        definition: orderSupplier;paymentEventConsumer;inventoryEventConsumer
      bindings:
        orderSupplier-out-0:
          destination: order-event
        paymentEventConsumer-in-0:
          destination: payment-event
        inventoryEventConsumer-in-0:
          destination: inventory-event
server:
  port: 8083


logging:
  level:
    org.springframework.boot.env: DEBUG    # Shows config loading
    org.springframework.core.env: DEBUG    # Shows property resolution
    com.hipradeep: TRACE                   # Your package for custom logging