server:
  port: 8080

spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: false
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true         # Enable route generation via serviceId
          lower-case-service-id: true
      routes:
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: lb://user-service   # lb:// = load balanced via Eureka
          predicates:
            - Path=/api/users/**        # Route requests starting with /user
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**


logging:
  level:
    org.springframework.boot.env: DEBUG    # Shows config loading
    org.springframework.core.env: DEBUG    # Shows property resolution
    com.hipradeep: TRACE                   # Your package for custom logging