spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_database
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    function:
      scan:
        enabled: false
    stream:
      function:
        definition: inventoryProcessor
      bindings:
        inventoryProcessor-in-0:
          destination: payment-event
        inventoryProcessor-out-0:
          destination: inventory-event
server:
  port: 8084