server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config/    #read file from resource/config/...
            - file:./config/        #read file from config-server/config/...(in same folder where jar runs)
            - file:../config/       #../config/...(one folder above where jar runs)
            - optional:classpath:/shared-config/
  profiles:
    active: native

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8771/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: false
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}

# Logging Configuration
logging:
  level:
    org.springframework.cloud.config: DEBUG
    com.hipradeep: TRACE
  file:
    name: logs/config-server.log